modLoader="javafml"
license="Apache-2.0"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/Trins-mods/Trins-Wiki-Lib/issues"

[[mods]]
modId="trins_wiki_lib"
version="${version}"
displayName="Trins Wiki Lib"
displayURL="https://github.com/Trins-mods/Trins-Wiki-Lib/"
credits="The Forge and FML guys for forge"
authors="Trinsdar"
description='''Just a lib shared by my addons for better ic2c wiki entries.'''
[[dependencies.trins_wiki_lib]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.34,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.trins_wiki_lib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.trins_wiki_lib]]
    modId="ic2"
    mandatory=true
    versionRange="[1.19.2-2.0.7,)"
    ordering="AFTER"
    side="BOTH"